AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'carpool

  Sample SAM Template for dynamo-db-crud

  '
Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'''
      AllowOrigin: '''*'''
      AllowCredentials: '''*'''
Resources:
  carpolFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: carpolFunction
      Handler: helloWorld.App::handleRequest
      Runtime: java11
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: UserTable
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:Query
          - dynamodb:Scan
          Resource:
            Fn::GetAtt:
            - UserTable
            - Arn
      Architectures:
      - x86_64
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        carpolFunction:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.carpolFunction746eafb8DepLayer
    Metadata:
      SamResourceId: carpolFunction
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: usersDB
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: E:\aws projects\carpol\.aws-sam\auto-dependency-layer\adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  carpolFunctionApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  DynamoDBTableName:
    Value:
      Ref: UserTable
    Description: DynamoDB Table Name
