package hitchify.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.Instant;

@DynamoDBTable(tableName = "BookingTable")
public class Booking {

    @DynamoDBHashKey(attributeName = "bookingId")
    @DynamoDBAutoGeneratedKey
    private String bookingId;

    @DynamoDBAttribute(attributeName = "fare")
    private double fare;

    @DynamoDBAttribute(attributeName = "dateTime")
    private String dateTime;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "providerId")
    private String providerId;

    @DynamoDBAttribute(attributeName = "timestamp")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Instant timestamp;


    public String getBookingId() {
        return "Booking:" + bookingId;
    }
    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }


    public double getFare() {
        return fare;
    }
    public void setFare(double fare) {
        this.fare = fare;
    }


    public String getDateTime() {
        return dateTime;
    }
    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }


    public String getUserId() {
        return userId;
    }
    public void setUserId(String userId) {
        this.userId = userId;
    }


    public String getProviderId() {
        return providerId;
    }
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }


    public Instant getTimestamp() {
        return timestamp;
    }
    public void setTimestamp(Instant timestamp) {
        this.timestamp = timestamp;
    }


}
