package hitchify.model;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "RidesTable")
public class Ride {

    @DynamoDBHashKey(attributeName = "rideId")
    @DynamoDBAutoGeneratedKey
    private String rideId;

    @DynamoDBAttribute(attributeName = "providerId")
    private String providerId;

    @DynamoDBAttribute(attributeName = "originAddress")
    private String originAddress; // Renamed from startAddress

    @DynamoDBAttribute(attributeName = "destinationAddress")
    private String destinationAddress; // Renamed from endAddress

    @DynamoDBAttribute(attributeName = "rideDate")
    private String rideDate;

    @DynamoDBAttribute(attributeName = "rideTime")
    private String rideTime;

    @DynamoDBAttribute(attributeName = "fare")
    private double fare;

    @DynamoDBAttribute(attributeName = "carType")
    private String carType;

    @DynamoDBAttribute(attributeName = "availableSeats")
    private int availableSeats;

    @DynamoDBAttribute(attributeName = "message")
    private String message;

    @DynamoDBAttribute(attributeName = "instantBooking")
    private boolean instantBooking;

    @DynamoDBAttribute(attributeName = "passengers")
    private List<String> passengers;


    public String getRideId() {
        return "Ride:" + rideId;
    }
    public void setRideId(String rideId) {
        this.rideId = rideId;
    }


    public String getProviderId() {
        return providerId;
    }
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }


    public String getOriginAddress() {
        return originAddress;
    }
    public void setOriginAddress(String originAddress) {
        this.originAddress = originAddress;
    }


    public String getDestinationAddress() {
        return destinationAddress;
    }
    public void setDestinationAddress(String destinationAddress) {
        this.destinationAddress = destinationAddress;
    }


    public String getRideDate() {
        return rideDate;
    }
    public void setRideDate(String rideDate) {
        this.rideDate = rideDate;
    }


    public String getRideTime() {
        return rideTime;
    }
    public void setRideTime(String rideTime) {
        this.rideTime = rideTime;
    }


    public double getFare() {
        return fare;
    }
    public void setFare(double fare) {
        this.fare = fare;
    }


    public String getCarType() {
        return carType;
    }
    public void setCarType(String carType) {
        this.carType = carType;
    }


    public int getAvailableSeats() {
        return availableSeats;
    }
    public void setAvailableSeats(int availableSeats) {
        this.availableSeats = availableSeats;
    }


    public String getMessage() {
        return message;
    }
    public void setMessage(String message) {
        this.message = message;
    }


    public boolean isInstantBooking() {
        return instantBooking;
    }
    public void setInstantBooking(boolean instantBooking) {
        this.instantBooking = instantBooking;
    }


    public List<String> getPassengers() {
        return passengers;
    }
    public void setPassengers(List<String> passengers) {
        this.passengers = passengers;
    }


}
